openapi: 3.0.1
info:
  title: Patch types
  version: 1.0.0
servers: [ ]
paths: { }
components:
  schemas:

    CarrierPatchRequest:
      type: object
      description: Частичное обновление компании перевозчика.
      properties:
        name:
          title: Название компании
          description: Название компании
          type: string
          nullable: true
        phone:
          title: Телефон
          description: Телефон
          type: string
          nullable: true

    RoutePatchRequest:
      type: object
      description: Частичное обновление маршрута
      properties:
        departurePoint:
          title: Пункт отправления
          description: Пункт отправления
          type: string
          nullable: true
        destinationPoint:
          title: Пункт назначения
          description: Пункт назначения
          type: string
          nullable: true
        departureAt:
          title: Дата отправления
          description: Дата отправления
          type: string
          format: date-time
          nullable: true
        destinationAt:
          title: Дата прибытия
          description: Дата прибытия
          type: string
          format: date-time
          nullable: true
        carrierId:
          title: Идентификатор компании перевозчика
          description: Идентификатор компании перевозчика
          type: string
          format: uuid
          nullable: true
        durationMinutes:
          title: Длительность в минутах
          description: Длительность в минутах
          type: integer
          format: int32
          example: 100
          nullable: true

    TicketPatchRequest:
      type: object
      description: Частичное обновление билета.
      properties:
        routeId:
          title: Идентификатор маршрута
          description: Идентификатор маршрута, к которому относится билет
          type: string
          format: uuid
          nullable: true
        seatNumber:
          title: Номер места
          description: Номер места в транспортном средстве
          type: integer
          format: int32
          minimum: 1
          nullable: true
        price:
          title: Цена
          description: Цена билета
          type: number
          format: double
          minimum: 0
          nullable: true
        isPurchased:
          title: Признак занятости
          description: Признак, куплен ли билет (оплачен)
          type: boolean
          nullable: true
        purchasedById:
          title: Идентификатор пользователя
          description: Идентификатор пользователя, купившего билет
          type: string
          format: uuid
          nullable: true
        purchasedAt:
          title: Дата покупки
          description: Дата и время покупки билета
          type: string
          format: date-time
          nullable: true