openapi: 3.0.1
info:
  title: Types
  version: 1.0.0
servers: [ ]
paths: { }
components:
  schemas:

    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          title: Логин
          description: Логин
          type: string
        password:
          title: Пароль
          description: Пароль
          type: string

    LoginResponse:
      type: object
      required:
        - access_token
        - expires_in
        - refresh_token
        - token_type
      properties:
        access_token:
          title: Токен доступа
          description: Токен доступа
          type: string
        expires_in:
          title: Токен истекает через
          description: Token истекает через
          type: integer
        refresh_token:
          title: RefreshToken
          description: RefreshToken
          type: string
        token_type:
          title: Тип токена
          description: Тип токена
          type: string

    RefreshTokenRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string

    CommonResponse:
      type: object
      x-generic-parent: true
      additionalProperties: true
      description: Общий предок всех ответов
      properties:
        requestId:
          type: string
          format: uuid
          description: Идентификатор входящего запроса(UUID)

    ErrorResponse:
      type: object
      x-generic-parent: true
      additionalProperties: true
      description: Ответ сервера содержащий ошибку
      allOf:
        - $ref: "#/components/schemas/CommonResponse"
        - properties:
            message:
              type: string
              description: Системное сообщение.
            userMessage:
              type: string
              description: Сообщение для отображения пользователю.

    CreateCarrierRequest:
      type: object
      required:
        - name
        - phone
      properties:
        name:
          title: Название компании
          description: Название компании
          type: string
        phone:
          title: Телефон
          description: Телефон
          type: string

    CreateCarrierResponse:
      type: object
      required:
        - id
        - name
        - phone
      properties:
        id:
          title: Идентификатор компании перевозчика
          description: Идентификатор компании перевозчика
          type: string
          format: uuid
        name:
          title: Название компании
          description: Название компании
          type: string
        phone:
          title: Телефон
          description: Телефон
          type: string
        createdAt:
          title: Дата создания
          description: Дата создания
          type: string
          format: date-time
        updatedAt:
          title: Дата обновления
          type: string
          format: date-time

    Pageable:
      description: Типовой объект постраничного запроса
      type: object
      properties:
        page:
          type: integer
          format: int32
          default: 0
          description: Номер страницы для постраничного вывода
        size:
          type: integer
          format: int32
          default: 20
          description: Размер страницы для постраничного вывода
        sort:
          type: array
          items:
            type: string
          description: Признак сортировки в формате "property,asc" или "property,desc". Может быть передано несколько признаков.

    CarriersSearchRequest:
      type: object
      properties:
        query:
          title: Быстрый поиск
          description: Поиск по ilike по полям name, phone
          type: string
        name:
          description: Название
          type: string
        phone:
          description: Телефон
          type: string
        createDateFrom:
          description: Дата создания с
          type: string
          format: date
        createDateTo:
          description: Дата создания по
          type: string
          format: date

    Page:
      description: Объект постраничного ответа org.springframework.data.domain.Page
      type: object
      properties:
        content:
          type: array
          items: { }
          description: Массив элементов текущей страницы
        last:
          type: boolean
          description: Признак последней страницы
        totalElements:
          type: integer
          format: int64
          description: Общее количество элементов
        totalPages:
          type: integer
          format: int32
          description: Общее количество страниц
        first:
          type: boolean
          description: Признак первой страницы
        numberOfElements:
          type: integer
          format: int32
          description: Количество элементов на текущей странице
        size:
          type: integer
          format: int32
          description: Размер страницы
        number:
          type: integer
          format: int32
          description: Номер текущей страницы
        empty:
          type: boolean
          description: Признак пустой страницы
