package com.example.ticketsmodule.impl.tickets.conversion;

import com.example.ticketsmodule.api.model.CreateTicketRequest;
import com.example.ticketsmodule.impl.routes.domain.RouteEntity;
import com.example.ticketsmodule.impl.tickets.domain.TicketEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

@DisplayName("TicketToEntityConverter unit tests")
class TicketToEntityConverterTest {

    private TicketToEntityConverter converter;

    private UUID routeId;
    private RouteEntity route;

    @BeforeEach
    void setUp() {
        converter = new TicketToEntityConverter();

        routeId = UUID.randomUUID();
        route = new RouteEntity();
        route.setId(routeId);
    }

    // ---------- маппинг полей ----------

    @Nested
    @DisplayName("field mapping")
    class FieldMappingTests {

        @Test
        @DisplayName("should map route, seatNumber and price from request")
        void shouldMapRouteSeatNumberAndPrice() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(15);
            request.setPrice(BigDecimal.valueOf(250));

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity).isNotNull();
            assertThat(entity.getRoute()).isSameAs(route);
            assertThat(entity.getSeatNumber()).isEqualTo(15);
            assertThat(entity.getPrice()).isEqualByComparingTo(BigDecimal.valueOf(250));
        }
    }

    // ---------- значения по умолчанию ----------

    @Nested
    @DisplayName("default values")
    class DefaultValuesTests {

        @Test
        @DisplayName("should set isPurchased=false by default")
        void shouldSetIsPurchasedFalse() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(1);
            request.setPrice(BigDecimal.ONE);

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity.isPurchased()).isFalse();
        }

        @Test
        @DisplayName("should set user=null by default")
        void shouldSetUserNull() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(1);
            request.setPrice(BigDecimal.ONE);

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity.getUser()).isNull();
        }

        @Test
        @DisplayName("should set purchasedAt=null by default")
        void shouldSetPurchasedAtNull() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(1);
            request.setPrice(BigDecimal.ONE);

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity.getPurchasedAt()).isNull();
        }

        @Test
        @DisplayName("should set id=null (generated by DB)")
        void shouldSetIdNull() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(1);
            request.setPrice(BigDecimal.ONE);

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity.getId()).isNull();
        }
    }

    // ---------- timestamps ----------

    @Nested
    @DisplayName("timestamps")
    class TimestampTests {

        @Test
        @DisplayName("should set createdAt and updatedAt")
        void shouldSetTimestamps() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(1);
            request.setPrice(BigDecimal.ONE);

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity.getCreatedAt()).isNotNull();
            assertThat(entity.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("should set createdAt close to updatedAt")
        void shouldSetTimestampsClose() {
            CreateTicketRequest request = new CreateTicketRequest();
            request.setSeatNumber(1);
            request.setPrice(BigDecimal.ONE);

            TicketEntity entity = converter.convert(request, route);

            assertThat(entity.getCreatedAt())
                    .isCloseTo(entity.getUpdatedAt(), within(1, ChronoUnit.SECONDS));
        }
    }
}