package com.example.ticketsmodule.impl.routes.conversion;

import com.example.ticketsmodule.api.model.CreateRouteRequest;
import com.example.ticketsmodule.api.model.CreateRouteResponse;
import com.example.ticketsmodule.impl.carriers.domain.CarrierEntity;
import com.example.ticketsmodule.impl.routes.domain.RouteEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("RouteMapper unit tests")
class RouteMapperTest {

    private RouteMapper mapper;

    private UUID routeId;
    private UUID carrierId;
    private CarrierEntity carrier;

    @BeforeEach
    void setUp() {
        mapper = new RouteMapperImpl();

        routeId = UUID.randomUUID();
        carrierId = UUID.randomUUID();

        carrier = new CarrierEntity();
        carrier.setId(carrierId);
        carrier.setName("Acme");
    }

    // ---------- toEntity() ----------

    @Nested
    @DisplayName("toEntity()")
    class ToEntityTests {

        @Test
        @DisplayName("should map all fields from request")
        void shouldMapAllFields() {
            LocalDateTime departureAt = LocalDateTime.now().plusDays(1);
            LocalDateTime destinationAt = departureAt.plusHours(2);

            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("Moscow");
            request.setDestinationPoint("SPb");
            request.setDurationMinutes(120);
            request.setDepartureAt(departureAt);
            request.setDestinationAt(destinationAt);

            RouteEntity entity = mapper.toEntity(request, carrier);

            assertThat(entity).isNotNull();
            assertThat(entity.getDeparturePoint()).isEqualTo("Moscow");
            assertThat(entity.getDestinationPoint()).isEqualTo("SPb");
            assertThat(entity.getDurationMinutes()).isEqualTo(120);
            assertThat(entity.getDepartureAt()).isEqualTo(departureAt);
            assertThat(entity.getDestinationAt()).isEqualTo(destinationAt);
        }

        @Test
        @DisplayName("should set carrier from argument, not from request")
        void shouldSetCarrierFromArgument() {
            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("A");
            request.setDestinationPoint("B");
            request.setDurationMinutes(60);
            request.setDepartureAt(LocalDateTime.now());
            request.setDestinationAt(LocalDateTime.now());

            RouteEntity entity = mapper.toEntity(request, carrier);

            assertThat(entity.getCarrier()).isSameAs(carrier);
            assertThat(entity.getCarrier().getId()).isEqualTo(carrierId);
        }

        @Test
        @DisplayName("should ignore id (generated by DB)")
        void shouldIgnoreId() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = mapper.toEntity(request, carrier);

            assertThat(entity.getId()).isNull();
        }

        @Test
        @DisplayName("should ignore createdAt")
        void shouldIgnoreCreatedAt() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = mapper.toEntity(request, carrier);

            assertThat(entity.getCreatedAt()).isNull();
        }

        @Test
        @DisplayName("should ignore updatedAt")
        void shouldIgnoreUpdatedAt() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = mapper.toEntity(request, carrier);

            assertThat(entity.getUpdatedAt()).isNull();
        }

        @Test
        @DisplayName("should return null when both sources are null")
        void shouldReturnNullWhenSourceNull() {
            RouteEntity entity = mapper.toEntity(null, null);

            assertThat(entity).isNull();
        }

        @Test
        @DisplayName("should accept null carrier")
        void shouldAcceptNullCarrier() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = mapper.toEntity(request, null);

            assertThat(entity).isNotNull();
            assertThat(entity.getCarrier()).isNull();
        }

        @Test
        @DisplayName("should handle empty strings")
        void shouldHandleEmptyStrings() {
            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("");
            request.setDestinationPoint("");
            request.setDurationMinutes(0);
            request.setDepartureAt(LocalDateTime.now());
            request.setDestinationAt(LocalDateTime.now());

            RouteEntity entity = mapper.toEntity(request, carrier);

            assertThat(entity.getDeparturePoint()).isEmpty();
            assertThat(entity.getDestinationPoint()).isEmpty();
        }
    }

    // ---------- toResponse() ----------

    @Nested
    @DisplayName("toResponse()")
    class ToResponseTests {

        @Test
        @DisplayName("should map all fields from entity")
        void shouldMapAllFields() {
            LocalDateTime departureAt = LocalDateTime.now().plusDays(1);
            LocalDateTime destinationAt = departureAt.plusHours(2);
            LocalDateTime created = LocalDateTime.now().minusDays(1);
            LocalDateTime updated = LocalDateTime.now();

            RouteEntity entity = RouteEntity.builder()
                    .id(routeId)
                    .departurePoint("Moscow")
                    .destinationPoint("SPb")
                    .carrier(carrier)
                    .durationMinutes(120)
                    .departureAt(departureAt)
                    .destinationAt(destinationAt)
                    .createdAt(created)
                    .updatedAt(updated)
                    .build();

            CreateRouteResponse response = mapper.toResponse(entity);

            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo(routeId);
            assertThat(response.getDeparturePoint()).isEqualTo("Moscow");
            assertThat(response.getDestinationPoint()).isEqualTo("SPb");
            assertThat(response.getDurationMinutes()).isEqualTo(120);
            assertThat(response.getDepartureAt()).isEqualTo(departureAt);
            assertThat(response.getDestinationAt()).isEqualTo(destinationAt);
            assertThat(response.getCreatedAt()).isEqualTo(created);
            assertThat(response.getUpdatedAt()).isEqualTo(updated);
        }

        @Test
        @DisplayName("should map carrier.id to carrierId")
        void shouldMapCarrierIdFromNestedCarrier() {
            RouteEntity entity = RouteEntity.builder()
                    .id(routeId)
                    .departurePoint("A")
                    .destinationPoint("B")
                    .carrier(carrier)
                    .durationMinutes(60)
                    .departureAt(LocalDateTime.now())
                    .destinationAt(LocalDateTime.now())
                    .build();

            CreateRouteResponse response = mapper.toResponse(entity);

            assertThat(response.getCarrierId()).isEqualTo(carrierId);
        }

        @Test
        @DisplayName("should return null when source is null")
        void shouldReturnNullWhenSourceNull() {
            CreateRouteResponse response = mapper.toResponse(null);

            assertThat(response).isNull();
        }

        @Test
        @DisplayName("should preserve null timestamps")
        void shouldPreserveNullTimestamps() {
            RouteEntity entity = RouteEntity.builder()
                    .id(routeId)
                    .departurePoint("A")
                    .destinationPoint("B")
                    .carrier(carrier)
                    .durationMinutes(60)
                    .departureAt(LocalDateTime.now())
                    .destinationAt(LocalDateTime.now())
                    .createdAt(null)
                    .updatedAt(null)
                    .build();

            CreateRouteResponse response = mapper.toResponse(entity);

            assertThat(response.getCreatedAt()).isNull();
            assertThat(response.getUpdatedAt()).isNull();
        }

        @Test
        @DisplayName("should preserve null id")
        void shouldPreserveNullId() {
            RouteEntity entity = RouteEntity.builder()
                    .departurePoint("A")
                    .destinationPoint("B")
                    .carrier(carrier)
                    .durationMinutes(60)
                    .departureAt(LocalDateTime.now())
                    .destinationAt(LocalDateTime.now())
                    .build();

            CreateRouteResponse response = mapper.toResponse(entity);

            assertThat(response.getId()).isNull();
        }

        @Test
        @DisplayName("should handle empty strings")
        void shouldHandleEmptyStrings() {
            RouteEntity entity = RouteEntity.builder()
                    .departurePoint("")
                    .destinationPoint("")
                    .carrier(carrier)
                    .durationMinutes(0)
                    .departureAt(LocalDateTime.now())
                    .destinationAt(LocalDateTime.now())
                    .build();

            CreateRouteResponse response = mapper.toResponse(entity);

            assertThat(response.getDeparturePoint()).isEmpty();
            assertThat(response.getDestinationPoint()).isEmpty();
        }
    }

    // ---------- round-trip ----------

    @Nested
    @DisplayName("round-trip")
    class RoundTripTests {

        @Test
        @DisplayName("request -> entity -> response should preserve main fields")
        void shouldPreserveFieldsOnRoundTrip() {
            LocalDateTime departureAt = LocalDateTime.now().plusDays(1);
            LocalDateTime destinationAt = departureAt.plusHours(2);

            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("Moscow");
            request.setDestinationPoint("SPb");
            request.setDurationMinutes(120);
            request.setDepartureAt(departureAt);
            request.setDestinationAt(destinationAt);

            RouteEntity entity = mapper.toEntity(request, carrier);
            entity.setId(routeId);
            entity.setCreatedAt(LocalDateTime.now());
            entity.setUpdatedAt(LocalDateTime.now());

            CreateRouteResponse response = mapper.toResponse(entity);

            assertThat(response.getDeparturePoint()).isEqualTo("Moscow");
            assertThat(response.getDestinationPoint()).isEqualTo("SPb");
            assertThat(response.getDurationMinutes()).isEqualTo(120);
            assertThat(response.getDepartureAt()).isEqualTo(departureAt);
            assertThat(response.getDestinationAt()).isEqualTo(destinationAt);
            assertThat(response.getCarrierId()).isEqualTo(carrierId);
        }
    }

    // ---------- helper ----------

    private static CreateRouteRequest createMinimalRequest() {
        CreateRouteRequest request = new CreateRouteRequest();
        request.setDeparturePoint("A");
        request.setDestinationPoint("B");
        request.setDurationMinutes(60);
        request.setDepartureAt(LocalDateTime.now());
        request.setDestinationAt(LocalDateTime.now());
        return request;
    }
}