package com.example.ticketsmodule.impl.routes.conversion;

import com.example.ticketsmodule.api.model.CreateRouteRequest;
import com.example.ticketsmodule.impl.carriers.domain.CarrierEntity;
import com.example.ticketsmodule.impl.routes.domain.RouteEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

@DisplayName("RouteToEntityConverter unit tests")
class RouteToEntityConverterTest {

    private RouteToEntityConverter converter;

    private UUID carrierId;
    private CarrierEntity carrier;

    @BeforeEach
    void setUp() {
        converter = new RouteToEntityConverter();

        carrierId = UUID.randomUUID();
        carrier = new CarrierEntity();
        carrier.setId(carrierId);
    }

    // ---------- маппинг полей ----------

    @Nested
    @DisplayName("field mapping")
    class FieldMappingTests {

        @Test
        @DisplayName("should map all fields from request to entity")
        void shouldMapAllFields() {
            LocalDateTime departureAt = LocalDateTime.now().plusDays(1);
            LocalDateTime destinationAt = departureAt.plusHours(2);

            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("Moscow");
            request.setDestinationPoint("SPb");
            request.setDurationMinutes(120);
            request.setDepartureAt(departureAt);
            request.setDestinationAt(destinationAt);

            RouteEntity entity = converter.convert(request, carrier);

            assertThat(entity).isNotNull();
            assertThat(entity.getDeparturePoint()).isEqualTo("Moscow");
            assertThat(entity.getDestinationPoint()).isEqualTo("SPb");
            assertThat(entity.getDurationMinutes()).isEqualTo(120);
            assertThat(entity.getDepartureAt()).isEqualTo(departureAt);
            assertThat(entity.getDestinationAt()).isEqualTo(destinationAt);
        }

        @Test
        @DisplayName("should set carrier from argument, not from request")
        void shouldSetCarrierFromArgument() {
            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("A");
            request.setDestinationPoint("B");
            request.setDurationMinutes(60);
            request.setDepartureAt(LocalDateTime.now());
            request.setDestinationAt(LocalDateTime.now());

            RouteEntity entity = converter.convert(request, carrier);

            assertThat(entity.getCarrier()).isSameAs(carrier);
            assertThat(entity.getCarrier().getId()).isEqualTo(carrierId);
        }
    }

    // ---------- значения по умолчанию ----------

    @Nested
    @DisplayName("default values")
    class DefaultValuesTests {

        @Test
        @DisplayName("should set id=null (generated by DB)")
        void shouldSetIdNull() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = converter.convert(request, carrier);

            assertThat(entity.getId()).isNull();
        }

        @Test
        @DisplayName("should set timestamps to now")
        void shouldSetTimestamps() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = converter.convert(request, carrier);

            assertThat(entity.getCreatedAt()).isNotNull();
            assertThat(entity.getUpdatedAt()).isNotNull();
            assertThat(entity.getCreatedAt())
                    .isCloseTo(entity.getUpdatedAt(), within(1, ChronoUnit.SECONDS));
        }
    }

    // ---------- edge cases ----------

    @Nested
    @DisplayName("edge cases")
    class EdgeCaseTests {

        @Test
        @DisplayName("should accept null carrier without throwing")
        void shouldAcceptNullCarrier() {
            CreateRouteRequest request = createMinimalRequest();

            RouteEntity entity = converter.convert(request, null);

            assertThat(entity).isNotNull();
            assertThat(entity.getCarrier()).isNull();
        }

        @Test
        @DisplayName("should preserve nullable fields as null when request has them null")
        void shouldPreserveNulls() {
            CreateRouteRequest request = new CreateRouteRequest();
            request.setDeparturePoint("A");
            request.setDestinationPoint("B");
            request.setDurationMinutes(60);
            request.setDepartureAt(null);
            request.setDestinationAt(null);

            RouteEntity entity = converter.convert(request, carrier);

            assertThat(entity.getDepartureAt()).isNull();
            assertThat(entity.getDestinationAt()).isNull();
        }
    }

    // ---------- helper ----------

    private static CreateRouteRequest createMinimalRequest() {
        CreateRouteRequest request = new CreateRouteRequest();
        request.setDeparturePoint("A");
        request.setDestinationPoint("B");
        request.setDurationMinutes(60);
        request.setDepartureAt(LocalDateTime.now());
        request.setDestinationAt(LocalDateTime.now());
        return request;
    }
}