package com.example.ticketsmodule.impl.carriers.conversion;

import com.example.ticketsmodule.api.model.CreateCarrierRequest;
import com.example.ticketsmodule.api.model.CreateCarrierResponse;
import com.example.ticketsmodule.impl.carriers.domain.CarrierEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("CarrierMapper unit tests")
class CarrierMapperTest {

    private CarrierMapper mapper;

    @BeforeEach
    void setUp() {
        mapper = new CarrierMapperImpl();
    }

    // ---------- toEntity() ----------

    @Nested
    @DisplayName("toEntity()")
    class ToEntityTests {

        @Test
        @DisplayName("should map name and phone from request")
        void shouldMapNameAndPhone() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme Transport");
            request.setPhone("+7-999-000-00-00");

            CarrierEntity entity = mapper.toEntity(request);

            assertThat(entity).isNotNull();
            assertThat(entity.getName()).isEqualTo("Acme Transport");
            assertThat(entity.getPhone()).isEqualTo("+7-999-000-00-00");
        }

        @Test
        @DisplayName("should ignore id (generated by DB)")
        void shouldIgnoreId() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme");
            request.setPhone("+7-000");

            CarrierEntity entity = mapper.toEntity(request);

            assertThat(entity.getId()).isNull();
        }

        @Test
        @DisplayName("should ignore createdAt")
        void shouldIgnoreCreatedAt() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme");
            request.setPhone("+7-000");

            CarrierEntity entity = mapper.toEntity(request);

            assertThat(entity.getCreatedAt()).isNull();
        }

        @Test
        @DisplayName("should ignore updatedAt")
        void shouldIgnoreUpdatedAt() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme");
            request.setPhone("+7-000");

            CarrierEntity entity = mapper.toEntity(request);

            assertThat(entity.getUpdatedAt()).isNull();
        }

        @Test
        @DisplayName("should return null when source is null")
        void shouldReturnNullWhenSourceNull() {
            CarrierEntity entity = mapper.toEntity(null);

            assertThat(entity).isNull();
        }

        @Test
        @DisplayName("should preserve null name and phone")
        void shouldPreserveNullStrings() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName(null);
            request.setPhone(null);

            CarrierEntity entity = mapper.toEntity(request);

            assertThat(entity).isNotNull();
            assertThat(entity.getName()).isNull();
            assertThat(entity.getPhone()).isNull();
        }

        @Test
        @DisplayName("should handle empty strings")
        void shouldHandleEmptyStrings() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("");
            request.setPhone("");

            CarrierEntity entity = mapper.toEntity(request);

            assertThat(entity.getName()).isEmpty();
            assertThat(entity.getPhone()).isEmpty();
        }
    }

    // ---------- toResponse() ----------

    @Nested
    @DisplayName("toResponse()")
    class ToResponseTests {

        @Test
        @DisplayName("should map all fields from entity")
        void shouldMapAllFields() {
            UUID id = UUID.randomUUID();
            LocalDateTime created = LocalDateTime.now().minusDays(1);
            LocalDateTime updated = LocalDateTime.now();

            CarrierEntity entity = CarrierEntity.builder()
                    .id(id)
                    .name("Acme Transport")
                    .phone("+7-999-000-00-00")
                    .createdAt(created)
                    .updatedAt(updated)
                    .build();

            CreateCarrierResponse response = mapper.toResponse(entity);

            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo(id);
            assertThat(response.getName()).isEqualTo("Acme Transport");
            assertThat(response.getPhone()).isEqualTo("+7-999-000-00-00");
            assertThat(response.getCreatedAt()).isEqualTo(created);
            assertThat(response.getUpdatedAt()).isEqualTo(updated);
        }

        @Test
        @DisplayName("should return null when source is null")
        void shouldReturnNullWhenSourceNull() {
            CreateCarrierResponse response = mapper.toResponse(null);

            assertThat(response).isNull();
        }

        @Test
        @DisplayName("should preserve null id")
        void shouldPreserveNullId() {
            CarrierEntity entity = CarrierEntity.builder()
                    .name("Acme")
                    .phone("+7-000")
                    .build();

            CreateCarrierResponse response = mapper.toResponse(entity);

            assertThat(response.getId()).isNull();
        }

        @Test
        @DisplayName("should preserve null timestamps")
        void shouldPreserveNullTimestamps() {
            CarrierEntity entity = CarrierEntity.builder()
                    .id(UUID.randomUUID())
                    .name("Acme")
                    .phone("+7-000")
                    .createdAt(null)
                    .updatedAt(null)
                    .build();

            CreateCarrierResponse response = mapper.toResponse(entity);

            assertThat(response.getCreatedAt()).isNull();
            assertThat(response.getUpdatedAt()).isNull();
        }

        @Test
        @DisplayName("should handle empty strings")
        void shouldHandleEmptyStrings() {
            CarrierEntity entity = CarrierEntity.builder()
                    .name("")
                    .phone("")
                    .build();

            CreateCarrierResponse response = mapper.toResponse(entity);

            assertThat(response.getName()).isEmpty();
            assertThat(response.getPhone()).isEmpty();
        }
    }

    // ---------- round-trip ----------

    @Nested
    @DisplayName("round-trip")
    class RoundTripTests {

        @Test
        @DisplayName("request -> entity -> response should preserve name and phone")
        void shouldPreserveFieldsOnRoundTrip() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme");
            request.setPhone("+7-000");

            CarrierEntity entity = mapper.toEntity(request);
            entity.setId(UUID.randomUUID());
            entity.setCreatedAt(LocalDateTime.now());
            entity.setUpdatedAt(LocalDateTime.now());

            CreateCarrierResponse response = mapper.toResponse(entity);

            assertThat(response.getName()).isEqualTo("Acme");
            assertThat(response.getPhone()).isEqualTo("+7-000");
        }
    }
}