package com.example.ticketsmodule.impl.carriers.conversion;

import com.example.ticketsmodule.api.model.CreateCarrierRequest;
import com.example.ticketsmodule.impl.carriers.domain.CarrierEntity;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.temporal.ChronoUnit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

@DisplayName("CarrierToEntityConverter unit tests")
class CarrierToEntityConverterTest {

    private CarrierToEntityConverter converter;

    @BeforeEach
    void setUp() {
        converter = new CarrierToEntityConverter();
    }

    // ---------- маппинг полей ----------

    @Nested
    @DisplayName("field mapping")
    class FieldMappingTests {

        @Test
        @DisplayName("should map name and phone from request")
        void shouldMapNameAndPhone() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme Transport");
            request.setPhone("+7-999-000-00-00");

            CarrierEntity entity = converter.convert(request);

            assertThat(entity).isNotNull();
            assertThat(entity.getName()).isEqualTo("Acme Transport");
            assertThat(entity.getPhone()).isEqualTo("+7-999-000-00-00");
        }
    }

    // ---------- значения по умолчанию ----------

    @Nested
    @DisplayName("default values")
    class DefaultValuesTests {

        @Test
        @DisplayName("should set id=null (generated by DB)")
        void shouldSetIdNull() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme");
            request.setPhone("+7-000");

            CarrierEntity entity = converter.convert(request);

            Assertions.assertNotNull(entity);
            assertThat(entity.getId()).isNull();
        }

        @Test
        @DisplayName("should set timestamps to now")
        void shouldSetTimestamps() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("Acme");
            request.setPhone("+7-000");

            CarrierEntity entity = converter.convert(request);

            Assertions.assertNotNull(entity);
            assertThat(entity.getCreatedAt()).isNotNull();
            assertThat(entity.getUpdatedAt()).isNotNull();
            assertThat(entity.getCreatedAt())
                    .isCloseTo(entity.getUpdatedAt(), within(1, ChronoUnit.SECONDS));
        }
    }

    // ---------- edge cases ----------

    @Nested
    @DisplayName("edge cases")
    class EdgeCaseTests {

        @Test
        @DisplayName("should preserve null name and phone")
        void shouldPreserveNullStrings() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName(null);
            request.setPhone(null);

            CarrierEntity entity = converter.convert(request);

            Assertions.assertNotNull(entity);
            assertThat(entity.getName()).isNull();
            assertThat(entity.getPhone()).isNull();
        }

        @Test
        @DisplayName("should handle empty strings")
        void shouldHandleEmptyStrings() {
            CreateCarrierRequest request = new CreateCarrierRequest();
            request.setName("");
            request.setPhone("");

            CarrierEntity entity = converter.convert(request);

            Assertions.assertNotNull(entity);
            assertThat(entity.getName()).isEmpty();
            assertThat(entity.getPhone()).isEmpty();
        }
    }
}