package com.example.ticketsmodule.impl.users.conversion;

import com.example.ticketsmodule.api.model.RegisterRequest;
import com.example.ticketsmodule.impl.users.convertion.RegisterUserToEntityConverter;
import com.example.ticketsmodule.impl.users.domain.UserEntity;
import com.example.ticketsmodule.impl.users.domain.UserRoleEnum;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.BDDAssertions.within;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@DisplayName("RegisterUserToEntityConverter unit tests")
class RegisterUserToEntityConverterTest {

    @Mock private PasswordEncoder passwordEncoder;

    @InjectMocks
    private RegisterUserToEntityConverter converter;

    private RegisterRequest request;

    @BeforeEach
    void setUp() {
        request = new RegisterRequest();
        request.setLogin("newuser");
        request.setPassword("raw-secret");
        request.setFullName("New User");
    }

    @Test
    @DisplayName("should map all fields from request to entity")
    void shouldMapAllFields() {
        when(passwordEncoder.encode("raw-secret")).thenReturn("$2a$10$encrypted");

        UserEntity entity = converter.convert(request);

        assertThat(entity).isNotNull();
        assertThat(entity.getLogin()).isEqualTo("newuser");
        assertThat(entity.getFullName()).isEqualTo("New User");
    }

    @Test
    @DisplayName("should encode password before setting it")
    void shouldEncodePassword() {
        when(passwordEncoder.encode("raw-secret")).thenReturn("$2a$10$encrypted");

        UserEntity entity = converter.convert(request);

        assertThat(entity.getPassword()).isEqualTo("$2a$10$encrypted");
        assertThat(entity.getPassword()).isNotEqualTo("raw-secret");
        verify(passwordEncoder).encode("raw-secret");
    }

    @Test
    @DisplayName("should always set role to USER")
    void shouldSetRoleToUser() {
        when(passwordEncoder.encode(anyPassword())).thenReturn("encrypted");

        UserEntity entity = converter.convert(request);

        assertThat(entity.getRole()).isEqualTo(UserRoleEnum.USER);
    }

    @Test
    @DisplayName("should set createdAt and updatedAt to now")
    void shouldSetTimestamps() {
        when(passwordEncoder.encode(anyPassword())).thenReturn("encrypted");

        UserEntity entity = converter.convert(request);

        assertThat(entity.getCreatedAt()).isNotNull();
        assertThat(entity.getUpdatedAt()).isNotNull();
        // createdAt и updatedAt должны быть "почти одинаковыми" (в пределах секунды)
        assertThat(entity.getCreatedAt()).isCloseTo(entity.getUpdatedAt(),
                within(1, java.time.temporal.ChronoUnit.SECONDS));
    }

    @Test
    @DisplayName("should not set id (id is generated by DB)")
    void shouldNotSetId() {
        when(passwordEncoder.encode(anyPassword())).thenReturn("encrypted");

        UserEntity entity = converter.convert(request);

        assertThat(entity.getId()).isNull();
    }

    @Test
    @DisplayName("should call encoder exactly once")
    void shouldCallEncoderOnce() {
        when(passwordEncoder.encode(anyPassword())).thenReturn("encrypted");

        converter.convert(request);

        verify(passwordEncoder, org.mockito.Mockito.times(1)).encode("raw-secret");
    }

    // ---------- helper ----------

    private static String anyPassword() {
        return org.mockito.ArgumentMatchers.anyString();
    }
}