package com.example.ticketsmodule.impl.users.conversion;

import com.example.ticketsmodule.api.model.RegisterRequest;
import com.example.ticketsmodule.impl.users.domain.UserEntity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("RegisterMapper unit tests")
class RegisterMapperTest {

    private RegisterMapper mapper;

    @BeforeEach
    void setUp() {
        mapper = new RegisterMapperImpl();
    }

    // ---------- маппинг полей ----------

    @Nested
    @DisplayName("field mapping")
    class FieldMappingTests {

        @Test
        @DisplayName("should map login from request")
        void shouldMapLogin() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity).isNotNull();
            assertThat(entity.getLogin()).isEqualTo("newuser");
        }

        @Test
        @DisplayName("should map fullName from request")
        void shouldMapFullName() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName("Ivan Ivanov");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getFullName()).isEqualTo("Ivan Ivanov");
        }

        @Test
        @DisplayName("should map both login and fullName")
        void shouldMapBothFields() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("testuser");
            request.setPassword("secret");
            request.setFullName("Test User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getLogin()).isEqualTo("testuser");
            assertThat(entity.getFullName()).isEqualTo("Test User");
        }
    }

    // ---------- игнорируемые поля ----------

    @Nested
    @DisplayName("ignored fields")
    class IgnoredFieldsTests {

        @Test
        @DisplayName("should ignore id (generated by DB)")
        void shouldIgnoreId() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getId()).isNull();
        }

        @Test
        @DisplayName("should ignore password (encoded in service)")
        void shouldIgnorePassword() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("raw-secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getPassword()).isNull();
        }

        @Test
        @DisplayName("should ignore role (set in service)")
        void shouldIgnoreRole() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getRole()).isNull();
        }

        @Test
        @DisplayName("should ignore createdAt")
        void shouldIgnoreCreatedAt() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getCreatedAt()).isNull();
        }

        @Test
        @DisplayName("should ignore updatedAt")
        void shouldIgnoreUpdatedAt() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getUpdatedAt()).isNull();
        }
    }

    // ---------- edge cases ----------

    @Nested
    @DisplayName("edge cases")
    class EdgeCaseTests {

        @Test
        @DisplayName("should return null when source is null")
        void shouldReturnNullWhenSourceNull() {
            UserEntity entity = mapper.toEntity(null);

            assertThat(entity).isNull();
        }

        @Test
        @DisplayName("should preserve null login and fullName")
        void shouldPreserveNullStrings() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin(null);
            request.setPassword("secret");
            request.setFullName(null);

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity).isNotNull();
            assertThat(entity.getLogin()).isNull();
            assertThat(entity.getFullName()).isNull();
        }

        @Test
        @DisplayName("should handle empty strings")
        void shouldHandleEmptyStrings() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("");
            request.setPassword("");
            request.setFullName("");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getLogin()).isEmpty();
            assertThat(entity.getFullName()).isEmpty();
        }

        @Test
        @DisplayName("should preserve long fullName")
        void shouldPreserveLongFullName() {
            String longName = "A".repeat(255);

            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("secret");
            request.setFullName(longName);

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity.getFullName()).hasSize(255);
        }
    }

    // ---------- полный сценарий ----------

    @Nested
    @DisplayName("full scenario")
    class FullScenarioTests {

        @Test
        @DisplayName("should map only login and fullName, all other fields null")
        void shouldMapOnlyLoginAndFullName() {
            RegisterRequest request = new RegisterRequest();
            request.setLogin("newuser");
            request.setPassword("raw-secret");
            request.setFullName("New User");

            UserEntity entity = mapper.toEntity(request);

            assertThat(entity).isNotNull();

            // mapped
            assertThat(entity.getLogin()).isEqualTo("newuser");
            assertThat(entity.getFullName()).isEqualTo("New User");

            // ignored
            assertThat(entity.getId()).isNull();
            assertThat(entity.getPassword()).isNull();
            assertThat(entity.getRole()).isNull();
            assertThat(entity.getCreatedAt()).isNull();
            assertThat(entity.getUpdatedAt()).isNull();
        }
    }
}